### PR TITLE
changes for sqs and sns

### PR DESCRIPTION
**Pull request by MeroshiniRaja**
+1 : Configuration for catalogBatchProcess
+1 : SNS and SQS interaction
+1 : Configuration for SQS
+1 : Email configuration
+1 : Filter policy for SNS

FE link: https://d3gadp1idu5cc4.cloudfront.net
Import CSV: https://d3gadp1idu5cc4.cloudfront.net/admin/products

Email Subscription:
Email_Subscription

### CODE REVIEW

**Comment by HannaHerman** [comment]
I think architecture should look a bit other way:
From task: 

> Task 6.1
Create a lambda function called catalogBatchProcess under the same Serverless config file (i.e. serverless.yaml) of the Product Service which will be triggered by an SQS event.

So new handler catalogBatchProcess should be in product-service

And is there any FE link where I can look how it works on FE side?

**Comment by MeroshiniRaja** [comment]
> I think architecture should look a bit other way: From task:
> 
> > Task 6.1
> > Create a lambda function called catalogBatchProcess under the same Serverless config file (i.e. serverless.yaml) of the Product Service which will be triggered by an SQS event.
> 
> So new handler catalogBatchProcess should be in product-service
> 
> And is there any FE link where I can look how it works on FE side?

Thank you Hanna. I have changed the file structure for catalogBatchProcess and given the FE link https://d3gadp1idu5cc4.cloudfront.net/

**Comment by HannaHerman** [comment]
Pr looks good, suggested mark is 5. But there are some problems with CORS, it is not configured. File is not uploading and I can't see new uploaded products on FE

**Comment by HannaHerman** [comment]
Everything works fine after fixes, mark is 5, good job!

**Pull request merged**
